### ISSUE TITLE
Update the PDFs

### ISSUE THREAD

**Issue by deepak0405** [dufferzafar/geeksforgeeks.pdf#9]
The pdfs in the release section doesn't contain recently added questions, as the last version of the pdf was released in 2015. I tried generating updated pdfs, but I was facing a few issues. Can you please release updated pdfs, if you are free ?

**Comment by dufferzafar** [comment]
I am not! :disappointed: 

There's a LOT I want to do with this repo, but as you too can understand, I just can't find the time - between assignments, projects and preparing for the upcoming placements!

I should've done this in summer vacation, when I had time, but procrastination is a bitch.

**Comment by dufferzafar** [comment]
If you want to create issues for the problems you were facing, please go ahead.

**Comment by deepak0405** [comment]
The issue is resolved :smiley:  !!!. I am attaching the updated files. Sir, I have not seen your code, as understanding it will take some time. The code is only generating Binary Tree and Graph pdf, how to generate other pdf files?

[Binary Trees.pdf](https://github.com/dufferzafar/geeks-pdf/files/2340730/Binary.Trees.pdf)
[Graphs.pdf](https://github.com/dufferzafar/geeks-pdf/files/2340731/Graphs.pdf)

**Comment by dufferzafar** [comment]
Yeah, the code was never really in a position to be run / understood by other people. Which is one of the things I wanted to fix this time.

> The code is only generating Binary Tree and Graph pdf, how to generate other pdf files?

Ruko, let me have a look.

**Comment by dufferzafar** [comment]
> Ruko, let me have a look.

I had a *look*. 

Ghatiya code hai ekdum. Kuch samajh nahin aa raha. Ye hi nai pata kis order mein files execute karni hain.

**Comment by dufferzafar** [comment]
> We can close this issue for now.

Naah, I don't mind open issues. Close kar diya toh fir yaad hi nai rahega.

> We can work on it next sem, I would love to work with you. 

Cool! I'll see if I can at-least clean up the code a bit before this sem ends. 

Warna fir agle sem toh kar hi lenge. :)

**Comment by deepak0405** [comment]
Hey Rishi !!
Did you generate the pdf's using the above-mentioned way? I tried generating the DP pdf, the generated pdf was having one chapter for each code of the problem.
eg; 
Content : 
1. Longest Increasing Subsequence
2. c++
3. PHP
4. java
Here 3 chapters were generated for the same question.

**Comment by dufferzafar** [comment]
I'm working on these PDFs today btw. Like I'm downloading some pages, right now!

I'll start with topics I need first: Backtracking, Dynamic Programming etc.

Will then move onto other PDFs.

File new issues for every problem you're facing, today just might be your lucky day :stuck_out_tongue:

**Comment by deepak0405** [comment]
Which hostel are you from? I can help :smiley:

**Comment by dufferzafar** [comment]
I'm a day scholar, so live at the comfort of my home :P 

But I really could use some help. The script that was working two days ago, has now stopped working (something must've changed on the Geeks site.)

The problem is with `boilerpipy` - the cruft removal library we use.

I'm now looking at a bunch of alternatives and there are lots of them!

I tried `python-readability` but [it results in an error too.](https://github.com/buriy/python-readability/issues/108)

Parsing is hard!

**Comment by dufferzafar** [comment]
If you have some time, look at that issue, and see if you can find a library which we can use. 

The goal is to remove all sidebars etc. from a geeks page and just keep the main content - the one in the "middle" of the site.

Some libraries we could use:

* https://github.com/bookieio/breadability
* https://github.com/miso-belica/jusText
* https://github.com/misja/python-boilerpipe

**Comment by dufferzafar** [comment]
I got it to work. The result isn't as clean as I want though.

and I'm seeing that each language as separate chapter issue too now.

Working on fixing that.

**Comment by deepak0405** [comment]
Thanks for updating code :blush:
Can you share Microsoft pdf? I was getting some error while generating the pdf.
`PDF/Microsoft.pdf
[pandoc warning] Unable to convert `/tmp/tex2pdf.7312/f1ffce071d9d0b7b9dd616e7a8df1bcbe8389928.shtml' for use with pdflatex.
[pandoc warning] Unable to convert `/tmp/tex2pdf.7312/662c5b644f8044040644cbfed791208aba42ef1d.shtml' for use with pdflatex.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.7312/f1ffce071d
9d0b7b9dd616e7a8df1bcbe8389928.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4691 ...71d9d0b7b9dd616e7a8df1bcbe8389928.shtml}

pandoc: Error producing PDF`

**Comment by dufferzafar** [comment]
Believe it or not, it took me ~3 hours day before yesterday to fix this
error, when I was generating PDF for Graphs.

I got so frustrated that I just left it all.

I'll try to see if I can generate Microsoft one today.

**Comment by deepak0405** [comment]
I think the docs on the release page are sufficient ( latest dp pdf contains 3000+ pages, we won't be able to read it ). 

> Believe it or not, it took me ~3 hours day before yesterday to fix this error, when I was generating PDF for Graphs. I got so frustrated that I just left it all. I'll try to see if I can generate Microsoft one today.
No problem, Microsoft pdf is not that required.

**Comment by dufferzafar** [comment]
Yeah, DP is huge. Which other ones did you download?

I'm downloading and fixing Microsoft one. Will push it in some time.

**Comment by dufferzafar** [comment]
Fixing this one took me an hour, and sadly I can't even think of any way of automating this. I'll still write the steps here:

1. Instead of generating the PDF, generate a .tex file. Say `Microsoft.tex`
2. Run pandoc on the .tex file. See which line it is erroring on. Note it down!
3. Run pandoc once again. As soon as it finishes fetching all images and begins extracting. Press Ctrl + Z, to halt the process. 
4. Go to the temporary directory pandoc creates and view the `input.tex` file. Go to the line number you wrote down before.
5. See what text comes before / after this line. Note it down!
6. Now open your original .tex file (`Microsoft.tex`) and go the text you note down.
7. Remove all bad `\includegraphics` commands.
8. Run pandoc again, this time with your fingers crossed.

**Comment by dufferzafar** [comment]
@deepak0405 Download Microsoft PDF from here: https://github.com/dufferzafar/geeksforgeeks.pdf/releases/download/v2.1/Microsoft.pdf

**Comment by deepak0405** [comment]
> Thanks for updating code 
> Can you share Microsoft pdf? I was getting some error while generating the pdf.
> 
> `PDF/Microsoft.pdf
> [pandoc warning] Unable to convert /tmp/tex2pdf.7312/f1ffce071d9d0b7b9dd616e7a8df1bcbe8389928.shtml for use with pdflatex.
> [pandoc warning] Unable to convert /tmp/tex2pdf.7312/662c5b644f8044040644cbfed791208aba42ef1d.shtml for use with pdflatex.
> ! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.7312/f1ffce071d
> 9d0b7b9dd616e7a8df1bcbe8389928.shtml (no BoundingBox).
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type H for immediate help.
> ...
> l.4691 ...71d9d0b7b9dd616e7a8df1bcbe8389928.shtml}
> pandoc: Error producing PDF`
> 
> 1. I am attaching dp pdf, if you need it. Its not looking good as I used template.tex ( please also add jgm.tex to the source code).
>    [Dynamic-Programming.pdf](https://github.com/dufferzafar/geeksforgeeks.pdf/files/2438751/Dynamic-Programming.pdf)

Its here

**Comment by dufferzafar** [comment]
The new set of PDFs are now live: https://github.com/dufferzafar/geeksforgeeks.pdf/releases/tag/v2.0
